// GENERATED by scripts/gen-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerate with: npm run gen:migrations
//
// db/migrations/*.sql compiled into the bundle so the deployed atomic migration runner
// (POST /api/migrate) can apply them where DATABASE_URL actually exists. Kept honest by
// tests/unit/migrations-drift.test.ts.

export type Migration = { version: string; name: string; sql: string };

export const MIGRATIONS: Migration[] = [
  {
    version: "20260725010000",
    name: "20260725010000_events.sql",
    sql: `-- P1 — events foundation.
-- EXPAND-ONLY: creates a new table; no DROP / RENAME / type-narrow on live objects.
-- This file must stay byte-equivalent to SCHEMA_SQL in lib/schema.ts
-- (tests/unit/schema-drift.test.ts enforces it).
create table if not exists events (
  id serial primary key,
  title text not null,
  starts_at timestamptz not null,
  location text not null,
  created_at timestamptz not null default now()
);
`,
  },
  {
    version: "20260725020000",
    name: "20260725020000_attendees.sql",
    sql: `-- P4 — attendees (RSVPs).
-- EXPAND-ONLY: creates a new table + index; no DROP / RENAME / type-narrow on live objects.
-- This file must stay byte-equivalent to its half of SCHEMA_SQL in lib/schema.ts
-- (tests/unit/schema-drift.test.ts enforces it).
create table if not exists attendees (
  id serial primary key,
  event_id integer not null references events (id),
  name text not null,
  created_at timestamptz not null default now()
);

-- SEPARATE statement on purpose: Postgres will NOT accept lower(name) inside a
-- table-level UNIQUE constraint — case-insensitive uniqueness must be an expression index.
create unique index if not exists attendees_event_name_uniq
  on attendees (event_id, lower(name));
`,
  },
  {
    version: "20260726010000",
    name: "20260726010000_capacity_waitlist.sql",
    sql: `-- W1 — capacity + waitlist + venue. EXPAND-ONLY.
-- The "location" column is deliberately LEFT IN PLACE: the currently-deployed code still reads
-- it, and migrations deploy separately from code. Retiring it is a later CONTRACT migration, run
-- once no deployed version references it.
-- Note: no backticks in this file — it is mirrored verbatim into the SCHEMA_SQL template literal
-- in lib/schema.ts, and a backtick would terminate that literal.
alter table events add column if not exists capacity integer;
alter table events add column if not exists venue text;
update events set venue = location where venue is null;
create table if not exists waitlist (
  id serial primary key,
  event_id integer not null references events (id),
  name text not null,
  position integer not null,
  created_at timestamptz not null default now()
);
create unique index if not exists waitlist_event_name_uniq on waitlist (event_id, lower(name));
-- touched to force a new head SHA for injection 4
-- injection 4, tight race
`,
  },
];
