// GENERATED by scripts/gen-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerate with: npm run gen:migrations
//
// db/migrations/*.sql compiled into the bundle so the deployed atomic migration runner
// (POST /api/migrate) can apply them where DATABASE_URL actually exists. Kept honest by
// tests/unit/migrations-drift.test.ts.

export type Migration = { version: string; name: string; sql: string };

export const MIGRATIONS: Migration[] = [
  {
    version: "20260725010000",
    name: "20260725010000_events.sql",
    sql: `-- P1 — events foundation.
-- EXPAND-ONLY: creates a new table; no DROP / RENAME / type-narrow on live objects.
-- This file must stay byte-equivalent to SCHEMA_SQL in lib/schema.ts
-- (tests/unit/schema-drift.test.ts enforces it).
create table if not exists events (
  id serial primary key,
  title text not null,
  starts_at timestamptz not null,
  location text not null,
  created_at timestamptz not null default now()
);
`,
  },
  {
    version: "20260725020000",
    name: "20260725020000_attendees.sql",
    sql: `-- P4 — attendees (RSVPs).
-- EXPAND-ONLY: creates a new table + index; no DROP / RENAME / type-narrow on live objects.
-- This file must stay byte-equivalent to its half of SCHEMA_SQL in lib/schema.ts
-- (tests/unit/schema-drift.test.ts enforces it).
create table if not exists attendees (
  id serial primary key,
  event_id integer not null references events (id),
  name text not null,
  created_at timestamptz not null default now()
);

-- SEPARATE statement on purpose: Postgres will NOT accept lower(name) inside a
-- table-level UNIQUE constraint — case-insensitive uniqueness must be an expression index.
create unique index if not exists attendees_event_name_uniq
  on attendees (event_id, lower(name));
`,
  },
  {
    version: "20260726010000",
    name: "20260726010000_capacity_waitlist.sql",
    sql: `-- W1 — capacity + waitlist + venue. EXPAND-ONLY.
-- The "location" column is deliberately LEFT IN PLACE: the currently-deployed code still reads
-- it, and migrations deploy separately from code. Retiring it is a later CONTRACT migration, run
-- once no deployed version references it.
-- Note: no backticks in this file — it is mirrored verbatim into the SCHEMA_SQL template literal
-- in lib/schema.ts, and a backtick would terminate that literal.
alter table events add column if not exists capacity integer;
alter table events add column if not exists venue text;
update events set venue = location where venue is null;
create table if not exists waitlist (
  id serial primary key,
  event_id integer not null references events (id),
  name text not null,
  position integer not null,
  created_at timestamptz not null default now()
);
create unique index if not exists waitlist_event_name_uniq on waitlist (event_id, lower(name));
-- touched to force a new head SHA for injection 4
-- injection 4, tight race
`,
  },
  {
    version: "20260727010000",
    name: "20260727010000_sessions_checkin.sql",
    sql: `-- X1 — sessions + per-session check-in. STRICTLY EXPAND-ONLY.
-- Nothing here removes, renames, narrows or hard-constrains a live object: the atomic runner
-- lives inside the deployed app, so this migration is GUARANTEED to be applied while the
-- PREVIOUS build is still serving traffic. That build inserts only (event_id, name) into
-- attendees and orders by created_at, so attendees.session_id stays NULLABLE and created_at
-- stays in place. Making session_id NOT NULL and retiring created_at are later CONTRACT
-- migrations, run once no deployed build writes session-less attendees.
-- Note: no backticks in this file — it is mirrored verbatim into the SCHEMA_SQL template
-- literal in lib/schema.ts, and a backtick would terminate that literal.
create table if not exists sessions (
  id serial primary key,
  event_id integer not null references events (id),
  title text not null,
  starts_at timestamptz not null,
  room text,
  created_at timestamptz not null default now()
);

-- SEPARATE statement, and an EXPRESSION INDEX rather than a table-level UNIQUE: Postgres
-- will not accept lower(title) in a UNIQUE constraint, and a plain UNIQUE (event_id, title)
-- would happily accept "Keynote" alongside "keynote". Matches attendees_event_name_uniq
-- and waitlist_event_name_uniq.
create unique index if not exists sessions_event_title_uniq
  on sessions (event_id, lower(title));

-- Per-session attendance. NULLABLE on purpose (see the header): the live build cannot supply
-- it, and application code (X2) is what requires it on every new RSVP.
alter table attendees add column if not exists session_id integer references sessions (id);

-- Check-in. NULL means "not yet arrived".
alter table attendees add column if not exists checked_in_at timestamptz;

-- attendees.created_at is misleading — it is the moment someone RSVPed. Introduce the
-- accurate name ADDITIVELY and keep created_at: the live build selects and orders by it.
alter table attendees add column if not exists rsvped_at timestamptz default now();

-- Backfill the accurate timestamp from the row's real RSVP moment. Scoped, and idempotent.
-- The second disjunct is load-bearing: Postgres 11+ fills existing rows with the evaluated
-- DEFAULT when the column is added, so pre-existing attendees arrive here stamped with the
-- migration time (rsvped_at > created_at) rather than NULL. Rows written by either build get
-- both timestamps from the same transaction clock, so they are equal and never rewritten.
update attendees
   set rsvped_at = created_at
 where rsvped_at is null
    or rsvped_at > created_at;

-- LEGACY BACKFILL — one General Admission session per event, so historical attendance is
-- attributed rather than invisible (X4 would otherwise undercount). Idempotent (insert ...
-- where not exists, keyed on event + lower(title)).
-- Deliberately NOT gated on "the event already has attendees": the INSERT and the UPDATE
-- below run in this one migration, but the OLD build is still serving traffic while it
-- applies. An event with no attendees at INSERT time would get no session; if the old build
-- then RSVPs into it, the UPDATE's exists-guard fails and that attendee's session_id stays
-- NULL forever, because this migration is ledger-recorded and never re-runs. Giving EVERY
-- event a session keeps that guard always satisfiable. Still expand-only — one extra row
-- per event, nothing removed or narrowed.
insert into sessions (event_id, title, starts_at, room)
select e.id, 'General Admission', e.starts_at, null::text
  from events e
 where not exists (
     select 1
       from sessions s
      where s.event_id = e.id
        and lower(s.title) = lower('General Admission')
   )
on conflict do nothing;

-- SCOPED update, never a blanket rewrite: only attendees that have no session yet, and only
-- where their event actually has a General Admission session to point at.
update attendees
   set session_id = (
     select s.id
       from sessions s
      where s.event_id = attendees.event_id
        and lower(s.title) = lower('General Admission')
      order by s.id
      limit 1
   )
 where session_id is null
   and exists (
     select 1
       from sessions s
      where s.event_id = attendees.event_id
        and lower(s.title) = lower('General Admission')
   );

-- DEMO FIXTURE — seeded THROUGH THIS MIGRATION, because POST /api/setup records no migration
-- versions and is a hard stop in this run: a fixture that only lived there could never
-- legitimately reach the hosted database.
-- Keyed on the FULL SEED_EVENTS identity from lib/schema.ts — title AND starts_at AND location,
-- not the display title alone. events has no unique constraint on title (real events may share
-- one), so a title-only join would attach these fixed demo dates and rooms to somebody's
-- unrelated event that merely happens to be called "Team Offsite Planning". starts_at is
-- compared as a timestamptz (the literal is cast), never as text. The join matching nothing is
-- the normal case, so this is a no-op unless the actual seed events are present.
--   · "Team Offsite Planning" gets TWO sessions at the SAME starts_at (the title tiebreak X3
--     asserts) plus a later one, and one of them has a NULL room.
--   · "Quarterly Demo Day" gets NO demo session here. Note carefully what that does and does
--     NOT mean: the legacy backfill ABOVE is deliberately unconditional over events, so every
--     event that exists when this migration applies — Quarterly Demo Day included — ends up
--     with exactly one session, "General Admission". This statement adds none to it, so it is
--     the MULTI-session demo surface it stays out of, not the one-session one. X3's
--     zero-session assertion therefore cannot use Quarterly Demo Day: it must drive an event
--     CREATED AFTER this migration applied. That is always available, because this migration
--     is ledger-recorded and runs exactly once, so nothing ever backfills a session into an
--     event created later.
-- Titles cannot collide case-insensitively with the legacy General Admission session above,
-- so an event may safely carry both.
insert into sessions (event_id, title, starts_at, room)
select e.id, v.title, v.starts_at::timestamptz, v.room::text
  from events e
  join (
    values
      ('Team Offsite Planning', '2026-08-04T17:00:00.000Z', 'Valletta HQ — Room 2', 'Budget Review', '2026-08-04T17:00:00Z', 'Valletta HQ — Room 2'),
      ('Team Offsite Planning', '2026-08-04T17:00:00.000Z', 'Valletta HQ — Room 2', 'Roadmap Deep Dive', '2026-08-04T17:00:00Z', null),
      ('Team Offsite Planning', '2026-08-04T17:00:00.000Z', 'Valletta HQ — Room 2', 'Retro and Wrap-up', '2026-08-04T18:30:00Z', 'Valletta HQ — Room 3'),
      ('Open Source Meetup', '2026-08-11T18:30:00.000Z', 'Sliema Community Hall', 'Lightning Talks', '2026-08-11T18:30:00Z', 'Sliema Community Hall')
  ) as v (event_title, event_starts_at, event_location, title, starts_at, room)
    on v.event_title = e.title
   and e.starts_at = v.event_starts_at::timestamptz
   and e.location = v.event_location
 where not exists (
   select 1
     from sessions s
    where s.event_id = e.id
      and lower(s.title) = lower(v.title)
 )
on conflict do nothing;
`,
  },
  {
    version: "20260727020000",
    name: "20260727020000_reconcile_sessionless_attendees.sql",
    sql: `-- RECONCILIATION PASS — ordered step between X2's install and X4's install.
--
-- WHY THIS EXISTS. 20260727010000_sessions_checkin backfilled attendees.session_id at a single
-- point in time, but the build serving traffic at that moment was still the PRE-X2 one, which
-- had no notion of sessions and kept INSERTing attendees with session_id NULL. That window is
-- inherent to expand/contract in this sandbox: the migration runner lives inside the deployed
-- app, so the migration necessarily applies while the previous build is live. The window closed
-- when X2 deployed (8b36c16) — X2 writes session_id on every RSVP into a sessionful event — so
-- from here on no new session-less row can arrive for an event that has sessions.
--
-- X4 is the phase that would misreport them: it reports per-session attendance and a show-up
-- rate, so a row sitting at NULL is silently absent from its own event's session totals. Hence
-- this runs BEFORE X4 installs and AFTER X2 deployed. Earlier would be useless (the old writer
-- would still be running); later would mean X4's first report is already wrong.
--
-- WHAT IT DOES NOT DO. Attendees of an event that has NO sessions stay NULL, and that is
-- correct, not a miss: an event created after 20260727010000 applied gets no legacy session, so
-- there is nothing to attribute them to and session_id is nullable by design. The subquery
-- yields NULL for such an event, so the statement leaves those rows exactly as they were.
-- Post-condition to verify is therefore "no session-less attendee on an event that HAS a
-- session", not "no session-less attendee anywhere".
--
-- EXPAND-SAFE + IDEMPOTENT: a scoped UPDATE only. No DROP, no RENAME, no type narrowing, no
-- NOT NULL. Re-running it matches nothing, because every row it touches ceases to satisfy the
-- WHERE clause. session_id stays nullable — SET NOT NULL remains a later CONTRACT migration.
update attendees
   set session_id = (select s.id
                       from sessions s
                      where s.event_id = attendees.event_id
                        and lower(s.title) = lower('General Admission')
                      order by s.id
                      limit 1)
 where session_id is null;
`,
  },
];
